/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'f.bocahu' at '12/03/18 16:50' with Gradle 3.0
 *
 * @author f.bocahu, @date 12/03/18 16:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
